### ISSUE TITLE
Old dependencies

### ISSUE THREAD

**Issue by allavena** [Gazler/rapidash#24]
Hello,

Rapidash is pulling in what are now old dependencies. 
Using hashie 1.2.0 (now 3.4.2)
Using oauth2 0.9.4 (now 1.0.0)
Using rspec 2.99.0 (now 3.3.0)

The code still works with the updated gem. Tried to make it into a pull request, though I haven't figured out how to get the dependencies to still work for Ruby 1.8.7. I can give a look if you are interested in the PR.

André

**Comment by Gazler** [comment]
I have merged your pull requests and release 0.4.0 https://rubygems.org/gems/rapidash

Thanks for your contributions.
