### ISSUE TITLE
Covert this to Elixir

### ISSUE THREAD

**Issue by victorlcampos** [Gazler/rapidash#27]
Hi,
Do you think It's possible to use this idea in Elixir? If yes, I could try do this?

**Comment by Gazler** [comment]
Hi,

I haven't really thought about converting this to Elixir, it would certainly be possible to achieve something similar. If you look at https://github.com/edgurgel/httpoison#wrapping-httpoisonbase it has a little support for clients.

If you want to have a go at doing this then feel free to use this project as inspiration. :)

**Comment by victorlcampos** [comment]
Yes,
I'm pretty new in Elixir, but I will try =)
This gem is awesome.

**Comment by Gazler** [comment]
@victorlcampos Keep me posted if you make any progress on this.

**Comment by victorlcampos** [comment]
@Gazler, Ok Gazler...
Sry for did not reply, now I'm working on https://phoenixcast.herokuapp.com/, but next year (it's a joke in brazil) I will take this...

I'm wating need use github api, that is on my roadmap for phoenixcast.

**Comment by victorlcampos** [comment]
happy new year, I will start make this today =)

**Comment by victorlcampos** [comment]
https://github.com/victorlcampos/rapidax

**Comment by victorlcampos** [comment]
@Gazler, I'm going the right way?

**Comment by Gazler** [comment]
@victorlcampos Your structs certainly make sense. Good idea on allowing resource to be nested in the struct.

**Comment by victorlcampos** [comment]
@Gazler, thx... so I will continue on this path =)

**Comment by victorlcampos** [comment]
@Gazler, hi...
here my progress:
https://github.com/victorlcampos/rapidax

Could you help me to find a better way for this:
defstruct Rapidax.Client.Http.client_struct ++ [site: "http://jsonplaceholder.typicode.com"]

When I started I thinked some thing like:
defstruct %Rapidax.Client.Http {site: "http://jsonplaceholder.typicode.com" }

**Comment by Gazler** [comment]
@victorlcampos If all of the Client fields are required in the HTTP struct, why not nest the struct? It took me a while to work out where `struct_fields` came from. Don't forget that explicit is better than implicit:

```
defstruct client: %Rapidax.Client{}, username: nil, password: nil
```

**Comment by victorlcampos** [comment]
Yes, i agree.
My initial idea was create new struct based on old struct. Some thing like this question:
http://stackoverflow.com/questions/32847464/struct-reuse-for-modules-in-elixir

``` elixir
defstruct %Rapidax.Client{} ++ [username: nil, password: nil]
```

Something like this...
becauce I want that %Rapidax.Client.Http{} has all Rapidax.Client attribute, not a client attribute with all attributes inside.

**Comment by victorlcampos** [comment]
But I agree this is very(very) ugly...
I opened a topic on elixir group mailing for discovery the best way to sove this:

https://groups.google.com/forum/#!topic/elixir-lang-core/BH4N_OgtBWA
